env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - secure: OQR++Fdd4QL2qSCTChrWHyBQDwWAfcbupveh+c7EEZO6Gb+8OMEQLKX50rr9MzLvr64BTbFBS9yJEBAcyQUxQFJRM0qfJlT6dkkm2Kfp+FagIOQmz9f7PQhf/NNPyR0RxxkpEkd4OeQUy8bcPq0xhBV9WzviZo8fh7WLoeejfaU=
install:
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - rustc -v
script:
  - cargo build
  - cargo test
  - cargo doc
  - cp -R target/doc ./doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
