[package]

name = "lettre"
version = "0.6.1"
description = "Email client"
readme = "README.md"
documentation = "https://docs.rs/lettre/"
repository = "https://github.com/lettre/lettre"
license = "MIT"
authors = ["Alexis Mousset <contact@amousset.me>"]
keywords = ["email", "smtp", "mailer"]

[dependencies]
bufstream = "0.1"
email = "0.0"
log = "0.3"
mime = "0.2"
openssl = "0.8"
rustc-serialize = "0.3"
rust-crypto = "0.2"
time = "0.1"
uuid = { version = "0.3", features = ["v4"] }
hyper = { version = "0.9", optional = true }
serde_urlencoded = { version = "0.2", optional = true }

[dev-dependencies]
env_logger = "0.3"

[features]
unstable = []
mailgun = ["hyper", "serde_urlencoded"]
