[package]

name = "lettre"
version = "0.6.3"
description = "Email client"
readme = "README.md"
documentation = "https://lettre.github.io/lettre/"
repository = "https://github.com/lettre/lettre"
license = "MIT"
authors = ["Alexis Mousset <contact@amousset.me>"]
keywords = ["email", "smtp", "mailer"]

[dependencies]
bufstream = "^0.1"
email = "^0.0"
log = "^0.3"
mime = "^0.2"
openssl = "> 0.9, < 0.11"
rustc-serialize = "^0.3"
rust-crypto = "^0.2"
time = "^0.1"
uuid = { version = "^0.4", features = ["v4"] }

[dev-dependencies]
env_logger = "^0.4"

[features]
unstable = []
